# default config values

[plugin]
# Minimum number of characters before showing suggestions
minWordLength = 2
# Maximum number of suggestions to show
maxSuggestions = 5
# Enable fuzzy matching for suggestion queries
fuzzyMatching = true
# Debounce time (ms) between keystrokes and suggestion fetch
debounceTime = 10
# Allow fast selection via digit keys
numberSelection = true

[internals]
# Maximum allowed characters for typing before suggestions hide
maxChars = 10
# Opacity for ghost hint overlay (0.0 to 1.0)
ghostHintOpacity = 0.5
