# Build  defaults based on my personal preferences

[plugin]
# Min number of chars before showing suggestions
minWordLength = 2
# Max number of suggestions to show
maxSuggestions = 24
# Time (ms) between keystrokes and suggestion fetch
debounceTime = 10
# Toggle fast selection via digit keys
numberSelection = true
# Always show suggestion rankings, even if digit selection is off
showRankingOverride = false
# Compact mode for tighter UI
compactMode = true
# Show ghost text in editor while typing
ghostTextEnabled = true
# Auto-insertion of suggestions while typing (on by default)
autoInsertion = true
# How auto-inserted suggestions are committed: "space-commits" or "enter-only"
autoInsertionCommitMode = "space-commits"
# Restore original word when pressing backspace after auto insertion
smartBackspace = true
# Font size for suggestions
fontSize = "editor"
# Font weight for suggestions
fontWeight = "normal"
# Debug mode for logging
debugMode = false
# Dictionary size in number of chunks (default: 5 chunks = 50k words)
dictionarySize = 5
# Enable abbreviations/shortcuts feature
abbreviationsEnabled = true
# Minimum prefix length for server-side completion
minPrefix = 2
# Maximum number of suggestions from server
maxLimit = 30

[abbreviations]
# Maximum length for shortcuts
maxShortcutLength = 10
# Maximum length for target phrases (in characters)
maxTargetLength = 4294967295
# Show notification when abbreviation is expanded
showNotification = false

[debug]
# Debug logging toggles (only active when debugMode = true)
msgpackData = false
menuRender = false
configChange = false
hotkeys = false
abbrEvents = false
renderEvents = false

[accessibility]
# Make suggestion suffix bold
boldSuffix = false
# Show all suggestions in uppercase
uppercaseSuggestions = false
# Prefix color intensity: "normal", "muted", "faint"
prefixColorIntensity = "faint"
# Ghost text color intensity: "normal", "muted", "faint"
ghostTextColorIntensity = "faint"

[internals]
# Max allowed chars for typing before suggestions hide
maxChars = 24

[limits]
minWordLength = { min = 1, max = 10 }
maxSuggestions = { min = 1, max = 180 }
debounceTime = { min = 1, max = 2000 }

[style]
# Padding for suggestion container (top/bottom, left/right)
padding = "6px 6px"
# Compact mode padding (tighter)
compact_padding = "3px 3px"
# Size (width/height/line-height) of the rank element
rank_size = 18
# Compact rank size (smaller)
compact_rank_size = 10
# Border radius of the rank element
rank_border_radius = "12%"
# Margin to the right of the rank element
rank_margin_right = 4
# Compact margin (tight)
compact_rank_margin_right = 2
# Background opacity of the rank element (in percent)
rank_bg_opacity = 12
# Background opacity of the selected rank element (in percent)
selected_rank_bg_opacity = 55

[keybinds]
# Default keybinds for navigation and actions
up = ["ArrowUp"]
down = ["ArrowDown"]
select = ["Enter"]
select_and_space = ["Tab"]
close = ["Escape"]
numberSelect = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

[keybind_modes]
# navigation modes
# default uses arrows only
# WIP: default is the only option for now
available = ["default"]
default = "default"

[autorespawn]
# Auto-respawn configuration to prevent memory bloat
enabled = true
# Respawn after this many suggestion requests
requestThreshold = 4000
# Respawn after this many minutes as fallback
timeThresholdMinutes = 120
