name: Release Plugin

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Init
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - name: Generate config files
        run: bun run scripts/init.ts

      - name: Build plugin
        run: bun run build

      - name: Get version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Verify files exist
        run: |
          if [ ! -f "main.js" ]; then
            echo "Error: main.js not found after build"
            exit 1
          fi
          if [ ! -f "manifest.json" ]; then
            echo "Error: manifest.json not found"
            exit 1
          fi
          if [ ! -f "styles.css" ]; then
            echo "Error: styles.css not found"
            exit 1
          fi
          echo "All required files are present:"
          ls -la main.js manifest.json styles.css

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --title="$tag" \
            --draft \
            main.js manifest.json styles.css
